# Custom Language File for Launcher Customizer

[ejs.app]
title = "HMSVR Launcher"

[ejs.landing]
mediaLinkURL = "#"
mediaGitHubURL = "https://github.com/gable3260/HMSVRLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/gable3260/HMSVRLauncher"
supportLink = "https://github.com/gable3260/HMSVRLauncher/issues"

[ejs.welcome]
welcomeHeader = "HM's Mod Server"
welcomeDescription = ""
welcomeDescCTA = ""
